create extension if not exists pgcrypto;

create table if not exists public.accounts (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  sync_id text not null,
  name text not null,
  type text not null check (type in ('Everyday', 'Savings')),
  goal_value numeric,
  goal_date timestamptz,
  created_at timestamptz not null,
  updated_at timestamptz not null,
  deleted_at timestamptz,
  unique (user_id, sync_id)
);

create index if not exists accounts_user_id_updated_at_idx on public.accounts (user_id, updated_at desc);

create table if not exists public.transactions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  sync_id text not null,
  value numeric not null,
  type text not null check (type in ('Income', 'Expense', 'Transfer', 'Bills')),
  name text not null default '',
  account_sync_id text not null,
  date timestamptz not null,
  category text,
  to_account_sync_id text,
  created_at timestamptz not null,
  updated_at timestamptz not null,
  deleted_at timestamptz,
  unique (user_id, sync_id)
);

create index if not exists transactions_user_id_updated_at_idx on public.transactions (user_id, updated_at desc);
create index if not exists transactions_user_id_account_sync_id_idx on public.transactions (user_id, account_sync_id);

create table if not exists public.settings (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  sync_id text not null,
  dark boolean not null default true,
  main_account_sync_id text,
  week_starting_day integer not null default 2,
  created_at timestamptz not null,
  updated_at timestamptz not null,
  deleted_at timestamptz,
  unique (user_id, sync_id)
);

create index if not exists settings_user_id_updated_at_idx on public.settings (user_id, updated_at desc);

alter table public.accounts enable row level security;
alter table public.transactions enable row level security;
alter table public.settings enable row level security;

drop policy if exists "Users manage own accounts" on public.accounts;
create policy "Users manage own accounts"
on public.accounts
for all
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "Users manage own transactions" on public.transactions;
create policy "Users manage own transactions"
on public.transactions
for all
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "Users manage own settings" on public.settings;
create policy "Users manage own settings"
on public.settings
for all
using (auth.uid() = user_id)
with check (auth.uid() = user_id);
