name: CI – Dev Branch

on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]

jobs:
  test-dev:
    runs-on: ubuntu-latest

    # strategy:
    #   # Run on the two Node versions you actually use locally.
    #   matrix:
    #     node: [18, 20]

    steps:
      - uses: actions/checkout@v4

      # Smart cache keyed on lock‑file hash
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      - run: npm ci

      - name: Lint
        run: npm run lint

      - name: Unit & component tests
        run: npm run test

      - name: Build (dev mode)
        run: npm run build:dev

      - name: Validate PWA manifest
        run: node scripts/checkPwa.js