name: CI – Prod Branch

on:
  push:
    branches: [main]

jobs:
  test-prod:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      - run: npm ci

      - name: Lint
        run: npm run lint

      - name: Unit & component tests
        run: npm run test

      - name: Build (prod mode)
        run: npm run build:prod

      - name: Validate PWA manifest
        run: node scripts/checkPwa.js