name: CI – Prod Branch

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  test-prod:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      - run: npm ci

      - name: Lint
        run: npm run lint

      - name: Unit & component tests
        run: npm run test

      - name: Build (prod mode)
        run: npm run build:prod

      - name: Validate PWA manifest
        run: node scripts/checkPwa.js

      - name: Deploy to Netlify
        if: github.event_name == 'push'
        uses: nwtgck/actions-netlify@v3.0
        with:
          publish-dir: './dist'
          production-branch: main
          production-deploy: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: "Prod deploy – ${{ github.sha }}"
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID:     ${{ secrets.NETLIFY_SITE_ID }}
      
      - name: Delete merged branch
        if: github.event_name == 'pull_request' && github.event.pull_request.merged == true
        run: |
          BRANCH_NAME="${{ github.event.pull_request.head.ref }}"
          REPO_NAME="${{ github.repository }}"
          echo "Deleting branch: $BRANCH_NAME"

          curl -X DELETE \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/repos/$REPO_NAME/git/refs/heads/$BRANCH_NAME